name: Release to production
on:
  release:
    types: [published]
jobs:
  call_build_and_push:
    uses: ./.github/workflows/build_and_push_image.yml
    with:
      image_name: ${{ github.repository }}
      image_tag: ${{ github.ref_name }}
    secrets: inherit
  deploy:
    needs: call_build_and_push
    uses: ./.github/workflows/update_terraform.yml
    with:
      image_tag: ${{ github.ref_name }}
      deployment_environment: production
    secrets: inherit